# Generated by Django 4.1.7 on 2023-03-21 12:28

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/ali.yildirim/projects/aiproject/asd')),
        ),
    ]
