# Generated by Django 4.1.7 on 2023-03-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_project_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='colorspace')),
            ],
        ),
    ]
